tap "nkzw-tech/tap"

brew "agent-browser"
brew "gh"
brew "git"
brew "git-delta"
brew "gnupg"
brew "herdr"
brew "mole"
brew "pinentry-mac"

cask "codiff"
cask "ghostty"
cask "font-hack-nerd-font"
cask "font-noto-sans-cjk-kr"
